### ISSUE TITLE
It is possible to draw outside of boundaries

### ISSUE THREAD

**Issue by madsane29** [4Q-s-r-o/signature#61]
It is not fixed. You still can draw outside of the boundaries to the right and to the bottom.

**Comment by madsane29** [comment]
I believe I fixed the problem. Pull Request here:

https://github.com/4Q-s-r-o/signature/pull/62

**Comment by crpo10** [comment]
its fixed or not? i have the same issue

**Comment by NitinSojitra** [comment]
I have the same issue.
User can draw right and bottom outside of signature pad.
Can you fix it or any solution for this issue?

**Comment by madsane29** [comment]
You can try out my fix if you add the following to your pubspec.yaml:

```
  signature:
    git:
      url: https://github.com/madsane29/signature
      ref: fix-draw-outside-of-canvas
```

Or if you download the modified signature.dart and add it to your project.
